# Stub backend Nova — derrière Velocity (ne pas exposer ce port aux joueurs).
server-port=25565
server-ip=127.0.0.1
online-mode=false
motd=Nova UHC
max-players=80
white-list=false
spawn-protection=0
view-distance=8
difficulty=1
gamemode=0
level-name=world
enable-query=false
enable-rcon=false
network-compression-threshold=256
