configurations {
    extraLibs
    implementation.extendsFrom(extraLibs)
}

dependencies {
    implementation project(':core')
    implementation group: 'com.github.azbh111', name: 'spigot-1.8.8', version: 'R'
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

jar {
    archiveFileName.set("UHC3945.jar")
    from {
        configurations.extraLibs.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
